apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: organizr-sa
      labels:
        app: organizr
      namespace: media
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: organizr
      labels:
        app: organizr
    rules:
      - apiGroups:
          - ''
        resources:
          - pods
        verbs:
          - get
          - list
          - watch
          - delete
      - apiGroups:
          - ''
        resources:
          - pods/log
          - services
          - nodes
          - namespaces
          - persistentvolumes
          - persistentvolumeclaims
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - apps
        resources:
          - deployments
          - daemonsets
          - statefulsets
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - batch
        resources:
          - cronjobs
          - jobs
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
        resources:
          - deployments
          - daemonsets
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - apps
        resources:
          - deployments/scale
        verbs:
          - get
          - update
      - apiGroups:
          - extensions
        resources:
          - deployments/scale
        verbs:
          - get
          - update
      - apiGroups:
          - storage.k8s.io
        resources:
          - storageclasses
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - volumesnapshot.external-storage.k8s.io
        resources:
          - volumesnapshots
          - volumesnapshotdatas
        verbs:
          - list
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: organizr
      labels:
        app: organizr
    roleRef:
      kind: ClusterRole
      name: organizr
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: organizr-sa
        namespace: media

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: organizr
      labels:
        app: organizr
      namespace: media
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: organizr
      template:
        metadata:
          labels:
            name: organizr
            app: organizr
        spec:
          containers:
            - name: organizr
              env:
                - name: "TZ"
                  value: "America/New_York"
                - name: "PUID"
                  value: "1000"
                - name: "PGID"
                  value: "1000"
              #image: linuxserver/organizr-v2:latest
              image: robermar2/organizr:armv7
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 80
                  protocol: TCP
              volumeMounts:
                - name: media-ssd
                  mountPath: /config
                  subPath: "configs/organizr" 
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
          volumes:
            - name: media-ssd
              persistentVolumeClaim:
                claimName: media-ssd

  - apiVersion: v1
    kind: Service
    metadata:
      name: organizr
      labels:
        app: organizr
      namespace: media
    spec:
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
      selector:
        app: organizr
      type: LoadBalancer
