apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
      containers:
      - name: mariadb
        image: 'jc21/mariadb-aria:latest'
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql_root_password
                name: mariadb
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: mysql_database
                name: mariadb
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: mysql_user
                name: mariadb
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql_password
                name: mariadb
        volumeMounts:
          - name: mariadb-data
            mountPath: /var/lib/mysql
  
