replicaCount: 1

image:
  repository: "haugene/transmission-openvpn"
  tag: "2.10-armhf" # Suffixed by -armhf to pull the ARM image
  #tag: "latest-armhf" # Suffixed by -armhf to pull the ARM image
  pullPolicy: "IfNotPresent"

env:
  - name: OPENVPN_PROVIDER
    value: "TUNNELBEAR" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
  - name: OPENVPN_CONFIG
    value: "United States"
  # - name: OPENVPN_OPTS
  #   value: "--pull-filter ignore 'ifconfig-ipv6 '"
  - name: OPENVPN_USERNAME
    valueFrom: # Reference to the secret | openvpn.username
      secretKeyRef:
        name: "openvpn"
        key: "username"
  - name: OPENVPN_PASSWORD
    valueFrom: # Reference to the secret | openvpn.password
      secretKeyRef:
        name: "openvpn"
        key: "password"
  # - name: NORDVPN_PROTOCOL
  #   value: "TCP"
  # - name: NORDVPN_COUNTRY
  #   value: "US" # Country where we want to download over VPN
  # - name: NORDVPN_CATEGORY
  #   value: "P2P" # VPN Type
  - name: LOCAL_NETWORK
    value: "192.168.0.0/24,10.36.0.0/24,10.42.0.0/24,10.40.0.0/24"
  - name: TRANSMISSION_PEER_PORT
    value: "47444"
  - name: TRANSMISSION_DOWNLOAD_DIR
    value: "/downloads/transmission"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: "WEBPROXY_ENABLED"
    value: "false"
  - name: "CREATE_TUN_DEVICE"
    value: "false"
  # - name: "TRANSMISSION_WEB_UI"
  #   value: "combustion"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: "media-ssd-downloads"
    persistentVolumeClaim:
      claimName: "media-ssd-downloads" # PersistentVolumeClaim created earlier
  - name: "media-ssd-transmission"
    persistentVolumeClaim:
      claimName: "media-ssd-transmission" # PersistentVolumeClaim created earlier
  - name: "dev-tun" # Needed for VPN
    hostPath:
      path: "/dev/net/tun"
  - name: localtime
    hostPath:
      path: /etc/localtime
      type: ""

volumeMounts:
  - name: "media-ssd-transmission"
    mountPath: "/data"
    #subPath: "/" # Path /mnt/ssd/transmission where transmission writes the configuration
  - name: "media-ssd-downloads"
    mountPath: "/downloads/transmission"
    #subPath: "/" # Path /mnt/ssd/downloads where transmission downloads Torrents
  - name: "dev-tun"
    mountPath: "/dev/net/tun" # Needed for VPN

securityContext:
  allowPrivilegeEscalation: true
  privileged: true
  capabilities: # Needed for VPN
    add:
      - NET_ADMIN

podSecurityContext:
  sysctls:
  - name: net.ipv6.conf.all.disable_ipv6
    value: "0"

nodeSelector:
  kubernetes.io/hostname: k8s-node-07