apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd-plex-data"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "1000Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/plex-data"