apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "duplicati-backup-dest"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "200Gi"