apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: lidarr-sa
      labels:
        app: lidarr
      namespace: media
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: lidarr
      labels:
        app: lidarr
    rules:
      - apiGroups:
          - ''
        resources:
          - pods
        verbs:
          - get
          - list
          - watch
          - delete
      - apiGroups:
          - ''
        resources:
          - pods/log
          - services
          - nodes
          - namespaces
          - persistentvolumes
          - persistentvolumeclaims
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - apps
        resources:
          - deployments
          - daemonsets
          - statefulsets
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - batch
        resources:
          - cronjobs
          - jobs
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
        resources:
          - deployments
          - daemonsets
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - apps
        resources:
          - deployments/scale
        verbs:
          - get
          - update
      - apiGroups:
          - extensions
        resources:
          - deployments/scale
        verbs:
          - get
          - update
      - apiGroups:
          - storage.k8s.io
        resources:
          - storageclasses
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - volumesnapshot.external-storage.k8s.io
        resources:
          - volumesnapshots
          - volumesnapshotdatas
        verbs:
          - list
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: lidarr
      labels:
        app: lidarr
    roleRef:
      kind: ClusterRole
      name: lidarr
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: lidarr-sa
        namespace: media

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: lidarr
      labels:
        app: lidarr
      namespace: media
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: lidarr
      template:
        metadata:
          labels:
            name: lidarr
            app: lidarr
        spec:
          containers:
            - name: lidarr
              env:
                - name: "TZ"
                  value: "America/New_York"
                - name: "PUID"
                  value: "1000"
                - name: "PGID"
                  value: "1000"
              #image: linuxserver/lidarr-v2:latest
              image: robermar2/lidarr:armv7
              imagePullPolicy: Always
              securityContext:
                capabilities:
                  add:
                    - SYS_ADMIN
                    - SYSLOG
                    - DAC_READ_SEARCH
              ports:
                - name: http
                  containerPort: 8686
                  protocol: TCP
              volumeMounts:
                - name: media-ssd
                  mountPath: /config
                  subPath: "configs/lidarr" 
                - name: media-ssd
                  mountPath: "/downloads/transmission"
                  subPath: "downloads/transmission" # Path /mnt/ssd/media/downloads/transmission where sonarr picks up downloaded episodes
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
          volumes:
            - name: media-ssd
              persistentVolumeClaim:
                claimName: media-ssd

  - apiVersion: v1
    kind: Service
    metadata:
      name: lidarr
      labels:
        app: lidarr
      namespace: media
    spec:
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8686
      selector:
        app: lidarr
      type: ClusterIP
