apiVersion: v1
kind: PersistentVolume
metadata:
  name: "duplicati-backup-dest"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "200Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/duplicati-dest"