apiVersion: v1
kind: PersistentVolume
metadata:
  name: "duplicati-app-config-data"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/duplicati-config"