#cloud-config
# vim: syntax=yaml
#

# Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: rpi-server-01.local
manage_etc_hosts: true
# don't write debian.org into apt mirrors
apt_preserve_sources_list: true

resize_rootfs: true
growpart:
  mode: auto
  devices: ["/"]
  ignore_growroot_disabled: false

# You could modify this for your own user information
users:
  - name: revans
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    plain_text_passwd: pablo123
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

package_upgrade: true
package_update: true
package_reboot_if_required: true
packages:
  - ntp

# Static IP address
write_files:
  - content: |
      persistent
      # Generate Stable Private IPv6 Addresses instead of hardware based ones
      slaac private

      # static IP configuration:
      interface eth0
      static ip_address=192.168.68.200/24
      static routers=192.168.68.1
      static domain_name_servers=192.168.68.1 8.8.8.8

    path: /etc/dhcpcd.conf

# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'
  - 'systemctl restart docker'
  - 'ifup eth0'
  # Activate WiFi interface
#  - 'ifup wlan0'
