apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd-downloads"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "650Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/downloads"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd-transmission"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "190Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/transmission"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd-sonarr"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "11Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sonarr"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd-radarr"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/radarr"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd-lidarr"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/lidarr"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd-jackett"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/jackett"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd-mariadb"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mariadb"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd-nginxproxymanager"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/nginxproxymanager"